### ISSUE TITLE
issue: npm私有仓库的搭建

### ISSUE THREAD

**Issue by eyea** [hoc2019/blog#2]
你好，感谢您的文章分享，在学习中。

在[npm私有仓库的搭建.md](https://github.com/hoc2019/blog/blob/master/article/npm%E7%A7%81%E6%9C%89%E4%BB%93%E5%BA%93%E7%9A%84%E6%90%AD%E5%BB%BA.md) 可能需要简单更改一下:

1. CommonJS规范中应该
```js
function showName() {
    console.log(wang); // -> console.log(name);
}
```

2. 搜索 ‘以实现模块化开’ 少写个文字 ‘以实现模块化开发’

哈哈 撤了撤了~

**Comment by sl2782087** [comment]
谢谢提醒，已经修改了。
